const roles=["Data Engineer","ML Engineer","BI Developer","Data Analyst"];const typedRole=document.getElementById("typedRole");let r=0,c=0,del=false;function typeRole(){const w=roles[r];typedRole.textContent=w.slice(0,c);if(!del&&c<w.length)c++;else if(del&&c>0)c--;else{del=!del;if(!del)r=(r+1)%roles.length;}setTimeout(typeRole,del?65:110)}typeRole();

// IntersectionObserver used instead of animation libraries for lightweight reveals.
const io=new IntersectionObserver((entries)=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add("is-visible")),{threshold:.15});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

const skills={"Languages":[["Python","Proficient"],["SQL","Proficient"],["JavaScript","Advanced"]],"Cloud & Infra":[["AWS (S3, Glue, Lambda)","Advanced"],["Azure (ADF, Synapse, DP-300)","Advanced"]],"Databases":[["Snowflake","Advanced"],["PostgreSQL","Advanced"],["MySQL","Advanced"]],"BI Tools":[["Power BI (DAX, star schema)","Proficient"],["Tableau","Advanced"]],"ML/AI":[["Scikit-learn","Advanced"],["TensorFlow/Keras","Advanced"],["Gradient Boosting","Proficient"],["NLP Pipelines","Advanced"]],"Other":[["dbt","Advanced"],["Apache Spark","Familiar"],["Git","Proficient"],["Docker","Advanced"]]};
const skillGrid=document.getElementById('skillGrid');Object.entries(skills).forEach(([cat,list])=>{const card=document.createElement('article');card.className='skill-card';card.innerHTML=`<h3>${cat}</h3>${list.map(([n,l])=>`<p>${n} <span class="level">${l}</span></p>`).join('')}`;skillGrid.append(card)});

const projects=[{title:"AWS Cost Intelligence Dashboard",tags:["cloud","analytics"],impact:"Enabled multi-account spend visibility with anomaly alerts.",stack:"S3 · Glue · Lambda · QuickSight",metrics:"Cost drift alerts · Executive views"},{title:"Bank Churn Risk Classifier",tags:["ml"],impact:"AUC 0.88 with SHAP-powered decision transparency.",stack:"Python · Gradient Boosting · Flask",metrics:"AUC 0.88 · Explainability"},{title:"Sales Performance Analytics Platform",tags:["bi","analytics"],impact:"Executive dashboards built on star-schema data warehouse.",stack:"Power BI · DAX · SQL",metrics:"Cross-region KPI tracking"},{title:"Geopolitical Market Impact Dashboard",tags:["ml","analytics"],impact:"Real-time conflict event study on macro-sensitive assets.",stack:"MLP · Gradient Boosting · Streaming",metrics:"AUC 0.88 · Live feeds"},{title:"Student Performance ML Pipeline",tags:["ml","bi"],impact:"End-to-end ETL-to-model workflow with Tableau outputs.",stack:"Python · Ensemble ML · Tableau",metrics:"Automated ETL & scoring"}];
const projectGrid=document.getElementById('projectGrid');function renderProjects(f='all'){projectGrid.innerHTML='';projects.filter(p=>f==='all'||p.tags.includes(f)).forEach(p=>{const el=document.createElement('article');el.className='project-card';el.innerHTML=`<h3>${p.title}</h3><p>${p.impact}</p><p><strong>${p.stack}</strong></p><p class="level">${p.metrics}</p><p><a href="https://github.com/Ashish1916" target="_blank" rel="noreferrer">GitHub</a> · <a href="#" aria-label="Live demo unavailable">Live Demo</a></p>`;projectGrid.append(el)})}renderProjects();document.querySelectorAll('.filter button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter .is-active')?.classList.remove('is-active');b.classList.add('is-active');renderProjects(b.dataset.filter)}));

const c=document.getElementById('dataCanvas');const ctx=c.getContext('2d');let pts=[];function resize(){c.width=innerWidth;c.height=document.getElementById('home').offsetHeight;pts=Array.from({length:64},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35}))}function draw(){ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='rgba(14,165,233,.25)';for(let i=0;i<pts.length;i++){const p=pts[i];p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,1.1,0,Math.PI*2);ctx.fillStyle='rgba(37,99,235,.65)';ctx.fill();for(let j=i+1;j<pts.length;j++){const q=pts[j],dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy);if(d<120){ctx.globalAlpha=(1-d/120)*.35;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.globalAlpha=1}}}requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize);

const navToggle=document.querySelector('.nav__toggle'),navList=document.querySelector('.nav__list');navToggle?.addEventListener('click',()=>{const open=navList.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open));});
